### ISSUE TITLE
conda installation error

### ISSUE THREAD

**Issue by cjhong** [theislab/dca#32]
I installed the latest conda (conda 4.8.0).

I cannot install dca successfully.

(dca) xxx:~$ conda install -c bioconda dca
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                       

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package kopt conflicts for:
dca -> kopt
Package scanpy conflicts for:
dca -> scanpy
Package keras conflicts for:
dca -> keras[version='>=2.0.8']
Package numpy conflicts for:
dca -> numpy[version='>=1.7']
Package python conflicts for:
dca -> python[version='>=3.6']
Package scikit-learn conflicts for:
dca -> scikit-learn
Package six conflicts for:
dca -> six[version='>=1.10.0']
Package h5py conflicts for:
dca -> h5py
Package pandas conflicts for:
dca -> pandas

**Comment by ati-lz** [comment]
Hi,

I am just facing the same problem. previously I had the DCA installed and working fine. BUt now, after a while I get an error "cannot import name 'SON' from 'bson'" when I run the previously installed one, and also when I try to install the DCA again I get a lot of conflicts of dca with other packages as above!
`The following specifications were found to be incompatible with each other:

Package scanpy conflicts for:
dca -> scanpy
Package pandas conflicts for:
dca -> pandas
Package keras conflicts for:
dca -> keras[version='>=2.0.8']
Package readline conflicts for:....
...`

I have also tried to upgrade bson, but still I get the same error:
`(base) AtiMacbook:New_results alafzi$ dca test.csv test_dca_denoised
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/alafzi/anaconda3/bin/dca", line 11, in <module>
    sys.exit(main())
  File "/Users/alafzi/anaconda3/lib/python3.7/site-packages/dca/__main__.py", line 147, in main
    from . import train
  File "/Users/alafzi/anaconda3/lib/python3.7/site-packages/dca/train.py", line 25, in <module>
    from .hyper import hyper
  File "/Users/alafzi/anaconda3/lib/python3.7/site-packages/dca/hyper.py", line 6, in <module>
    from kopt import CompileFN, test_fn
  File "/Users/alafzi/anaconda3/lib/python3.7/site-packages/kopt/__init__.py", line 10, in <module>
    from . import hyopt
  File "/Users/alafzi/anaconda3/lib/python3.7/site-packages/kopt/hyopt.py", line 9, in <module>
    from hyperopt.mongoexp import MongoTrials
  File "/Users/alafzi/anaconda3/lib/python3.7/site-packages/hyperopt/mongoexp.py", line 117, in <module>
    from bson import SON
ImportError: cannot import name 'SON' from 'bson' (/Users/alafzi/.local/lib/python3.7/site-packages/bson/__init__.py)
`

Would be great if I can have a clue of what is happening...

Many thanks,

ATi
