### ISSUE TITLE
Use count data as input but encounter assertion error

### ISSUE THREAD

**Issue by elviswong1013** [theislab/dca#44]
DCA reports assertion errors when I use certain raw count scRNA-seq dataset as input.

Traceback (most recent call last):
  File "/home/Elvis/anaconda3/envs/dca-env/bin/dca", line 8, in <module>
    sys.exit(main())
  File "/home/Elvis/anaconda3/envs/dca-env/lib/python3.6/site-packages/dca/__main__.py", line 149, in main
    train.train_with_args(args)
  File "/home/Elvis/anaconda3/envs/dca-env/lib/python3.6/site-packages/dca/train.py", line 113, in train_with_args
    test_split=args.testsplit)
  File "/home/Elvis/anaconda3/envs/dca-env/lib/python3.6/site-packages/dca/io.py", line 69, in read_dataset
    assert np.all(X_subset.astype(int) == X_subset), norm_error
AssertionError: Make sure that the dataset (adata.X) contains unnormalized count data.

**Comment by gokceneraslan** [comment]
If it's really count data you can try `adata.X = adata.X.astype(int)` I think
