### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by sruthisrini** [theislab/dca#54]
After running the command "dca matrix.csv results" as per README.md, in the terminal, I am getting a bunch of errors.

Traceback (most recent call last):
  File "C:\Users\Sruthi Srinivasan\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Sruthi Srinivasan\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sruthi Srinivasan\PycharmProjects\pythonProject1\venv\Scripts\dca.exe\__main__.py", line 7, in <module>
  File "C:\Users\Sruthi Srinivasan\PycharmProjects\pythonProject1\venv\lib\site-packages\dca\__main__.py", line 152, in main
    from . import train
  File "C:\Users\Sruthi Srinivasan\PycharmProjects\pythonProject1\venv\lib\site-packages\dca\train.py", line 25, in <module>
    from .hyper import hyper
  File "C:\Users\Sruthi Srinivasan\PycharmProjects\pythonProject1\venv\lib\site-packages\dca\hyper.py", line 6, in <module>
    from kopt import CompileFN, test_fn
  File "C:\Users\Sruthi Srinivasan\PycharmProjects\pythonProject1\venv\lib\site-packages\kopt\__init__.py", line 10, in <module>
    from . import hyopt
  File "C:\Users\Sruthi Srinivasan\PycharmProjects\pythonProject1\venv\lib\site-packages\kopt\hyopt.py", line 13, in <module>
    from kopt.config import db_host, db_port, save_dir
  File "C:\Users\Sruthi Srinivasan\PycharmProjects\pythonProject1\venv\lib\site-packages\kopt\config.py", line 60, in <module>
    _config = yaml.load(open(_config_path))
TypeError: load() missing 1 required positional argument: 'Loader'

Could you please give a possible solution for this problem?

**Comment by WWXkenmo** [comment]
Hey,

Simply reverse the pyyaml package version back to  5.4.1, and you could solve the problem
```
pip install pyyaml==5.4.1
```

**Comment by arunhpatil** [comment]
This doesn't work. The problem still exists. 
I installed pyaml 5.4.1 and then tried `python -c "from dca.api import dca"  `
```
Successfully installed pyyaml-5.4.1
(patil) ahanuma2@eb-li-y0wj3pwh ~ % python -c "from dca.api import dca"                                       
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dca/api.py", line 15, in <module>
    from .train import train
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dca/train.py", line 25, in <module>
    from .hyper import hyper
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dca/hyper.py", line 6, in <module>
    from kopt import CompileFN, test_fn
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kopt/__init__.py", line 10, in <module>
    from . import hyopt
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kopt/hyopt.py", line 13, in <module>
    from kopt.config import db_host, db_port, save_dir
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kopt/config.py", line 60, in <module>
    _config = yaml.load(open(_config_path))
TypeError: load() missing 1 required positional argument: 'Loader'
```

Is there a fix for this? I use Mac M2. 

Thank you,
Arun.
