### ISSUE TITLE
--hyper

### ISSUE THREAD

**Issue by radio1988** [theislab/dca#6]
Hi theislab, 

I tried to use the `--hyper` parameter in dca, but running `dca -t --hyper pbmc.g949_c10k.msk90.csv hyper_dca`, 

But I got the following error:

```
/mnt/lfs2/rui/vir/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/mnt/lfs2/rui/vir/bin/dca", line 11, in <module>
    load_entry_point('DCA==0.1', 'console_scripts', 'dca')()
  File "/mnt/lfs2/rui/vir/lib/python3.5/site-packages/DCA/__main__.py", line 135, in main
    train.train_with_args(args)
  File "/mnt/lfs2/rui/vir/lib/python3.5/site-packages/DCA/train.py", line 103, in train_with_args
    hyper(args)
  File "/mnt/lfs2/rui/vir/lib/python3.5/site-packages/DCA/hyper.py", line 15, in hyper
    ds = io.create_dataset(args.input,
AttributeError: module 'DCA.io' has no attribute 'create_dataset'
```

**Comment by gokceneraslan** [comment]
Fixed now with version 0.1.1, you can install it using `pip install dca` command.
